server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    config:
      enabled: false

    gateway:
      mvc:
        routes:
          - id: user-service-route
            uri: http://localhost:8081
            predicates:
              - Path=/api/users/**
          - id: product-service-route
            uri: http://localhost:8082
            predicates:
            - Path=/api/products/**, /api/categories/**, /api/images/**
          - id: cart-service-route
            uri: http://localhost:8083
            predicates:
              - Path=/api/cart/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  security:
    oauth2:
      resourceserver:
        jwt:
          # C'est la ligne CRUCIALE qui corrige ton erreur "UnknownHostException"
          jwk-set-uri: http://localhost:9090/realms/humble-realm/protocol/openid-connect/certs

management:
  tracing:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true