server:
  port: 8761

spring:
  application:
    name: discovery-service
  cloud:
    config:
      enabled: false # On laisse ça désactivé tant que tu n'as pas le Config Server

eureka:
  client:
    register-with-eureka: false # Serveur ne s'enregistre pas lui-même
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 5 # Démarrage rapide