server:
  port: 8085

spring:
  application:
    name: payment

  datasource:
    # Lecture depuis le fichier .env
    url: ${DB_PAYMENT_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Sécurité Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          # On utilise aussi les variables ici pour être flexible
          jwk-set-uri: http://localhost:9090/realms/humble-realm/protocol/openid-connect/certs

# Configuration Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Config Custom pour Payment (URL du Order Service)
application:
  config:
    order-url: http://localhost:8084